# Generated by Django 2.2.12 on 2020-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='test', max_length=400),
            preserve_default=False,
        ),
    ]
